name: リリース

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: リリース
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: 依存関係のインストール
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Changeset アクションの実行
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "バージョンアップ"
          commit: "chore: バージョンアップ"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
